/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
});

export const idlService = IDL.Service({
  'add' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'addNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'echo' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'greet' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'increment' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
  });
  
  return IDL.Service({
    'add' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'addNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'echo' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'greet' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'increment' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };